/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDtoDescription } from './categoryDtoDescription';

export interface CategoryDto {
  /** Identificador único da categoria */
  id: string;
  /** Título da categoria */
  title: string;
  /**
     * Descrição da categoria
     * @nullable
     */
  description?: CategoryDtoDescription;
  /** Data de criação */
  createdAt: string;
  /** Data de última atualização */
  updatedAt: string;
}
