/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateCategoryDto {
  /**
     * Título da categoria
     * @minLength 2
     * @maxLength 60
     */
  title?: string;
  /**
     * Descrição da categoria
     * @maxLength 255
     */
  description?: string;
}
